import MainLayout from '@/components/MainLayout/MainLayout';
import '@/styles/globals.scss';
import type { AppProps } from 'next/app';
import { Poppins } from '@next/font/google';
import Head from 'next/head';

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Currency Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout className={poppins.className}>
        <Component {...pageProps} />
      </MainLayout>
    </>
  );
}
