import MainLayout from '@/components/MainLayout/MainLayout';
import '@/styles/globals.scss';
import type { AppProps } from 'next/app';
import localFont from '@next/font/local';
import Head from 'next/head';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { GetServerSidePropsContext } from 'next';
import { INITIAL_FROM_CURRENCY } from '../lib/constants';
import { GlobalContextProvider } from '@/contexts/globalContext';

const poppins = localFont({
  src: [
    {
      path: '../fonts/Poppins-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/Poppins-Regular.woff',
      weight: '400',
      style: 'normal',
    },
  ],
});

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
    background: {
      default: '#fff',
    },
  },
  typography: {
    fontFamily: 'inherit',
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <GlobalContextProvider>
      <ThemeProvider theme={darkTheme}>
        <Head>
          <title>Currency Exchange</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainLayout className={poppins.className}>
          <Component {...pageProps} />
        </MainLayout>
      </ThemeProvider>
    </GlobalContextProvider>
  );
}
